export interface Enquiry {
  id?: string;
  enquiryNumber: string;
  date: string;
  course: string;
  name: string;
  dob: string;
  gender: 'M' | 'F' | 'Other' | '';
  motherName: string;
  fatherName: string;
  address: string;
  mobile1: string;
  mobile2: string;
  email: string;
  class10Percent: string;
  class12Stream: string;
  class12Percent: string;
  physicsMarks: string;
  chemistryMarks: string;
  mathsMarks: string;
  biologyMarks: string;
  csMarks: string;
  schoolNameWithState: string;
  neetUgScore: string;
  neetPgScore: string;
  category: string;
  cuetScoreRank: string;
  cetScoreRank: string;
  clatScoreRank: string;
  catScoreRank: string;
  jeeMainsCrl: string;
  percentile: string;
  pcmPercent: string;
  pcbPercent: string;
  collegeUniversityName: string;
  courses: string;
  marks: string;
  reference: string;
  signatureDataUrl: string;
  answers?: Record<string, string>;
  termsAccepted?: boolean;
  termsAcceptedAt?: string;
  termsVersion?: string;
  privacyVersion?: string;
  clientIp?: string;
  pdfStoragePath?: string;
  status?: 'submitted' | 'error';
  createdAt?: unknown;
  updatedAt?: unknown;
}
