// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/enquiries" | "/admin/enquiries/[id]" | "/admin/login" | "/admin/pdf-mapping/test" | "/admin/search" | "/admin/settings" | "/enquiry" | "/enquiry/success"
type AppRouteHandlerRoutes = "/api/admin/enquiries" | "/api/admin/enquiries/[id]" | "/api/admin/enquiries/[id]/download" | "/api/admin/enquiries/[id]/pdf" | "/api/admin/pdf-mapping/preview" | "/api/admin/pdf-mappings" | "/api/admin/pdf-template" | "/api/admin/session" | "/api/admin/stats" | "/api/client-ip" | "/api/enquiries"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/enquiries": {}
  "/admin/enquiries/[id]": { "id": string; }
  "/admin/login": {}
  "/admin/pdf-mapping/test": {}
  "/admin/search": {}
  "/admin/settings": {}
  "/api/admin/enquiries": {}
  "/api/admin/enquiries/[id]": { "id": string; }
  "/api/admin/enquiries/[id]/download": { "id": string; }
  "/api/admin/enquiries/[id]/pdf": { "id": string; }
  "/api/admin/pdf-mapping/preview": {}
  "/api/admin/pdf-mappings": {}
  "/api/admin/pdf-template": {}
  "/api/admin/session": {}
  "/api/admin/stats": {}
  "/api/client-ip": {}
  "/api/enquiries": {}
  "/enquiry": {}
  "/enquiry/success": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
