var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/pdf-mapping/preview/route.js")
R.c("server/chunks/node_modules_next_36a6a1d1._.js")
R.c("server/chunks/node_modules_@supabase_auth-js_dist_module_02e1b12e._.js")
R.c("server/chunks/node_modules_pdf-lib_es_core_1c65b47f._.js")
R.c("server/chunks/node_modules_pdf-lib_es_api_9cdcbbc9._.js")
R.c("server/chunks/node_modules_pdf-lib_es_634d7e73._.js")
R.c("server/chunks/node_modules_pako_5efc97ef._.js")
R.c("server/chunks/node_modules_@pdf-lib_standard-fonts_es_0e490e76._.js")
R.c("server/chunks/node_modules_cb4cf8b8._.js")
R.c("server/chunks/[root-of-the-server]__8a5f951e._.js")
R.m("[project]/.next-internal/server/app/api/admin/pdf-mapping/preview/route/actions.js [app-rsc] (server actions loader, ecmascript)")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/admin/pdf-mapping/preview/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/admin/pdf-mapping/preview/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
