'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';

type Row = { id: string; enquiry_number: string; name: string; mobile1: string; email: string; course: string; created_at: string; status: string };
export function EnquiryList({ title = 'View all enquiries', searchOnly = false }: { title?: string; searchOnly?: boolean }) {
  const router = useRouter();
  const [rows, setRows] = useState<Row[]>([]); const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [page, setPage] = useState(1); const [total, setTotal] = useState(0);
  useEffect(() => { const params = new URLSearchParams({ search, status, page: String(page) }); fetch(`/api/admin/enquiries?${params}`).then(async response => { if (response.status === 401) router.replace('/admin/login'); else if (response.ok) { const result = await response.json(); setRows(result.data); setTotal(result.total); } }); }, [page, router, search, status]);
  const pageCount = Math.max(1, Math.ceil(total / 20));
  return <main className="admin-shell"><div className="container"><header className="admin-header"><div><p className="eyebrow">Workspace</p><h1>{title}</h1><p className="admin-subtitle">Find, review, and follow up on every student enquiry.</p></div></header><div className="filters"><input aria-label="Search enquiries" placeholder={searchOnly ? 'Search ID, name, course, mobile, or email' : 'Search by ID, name, course, mobile, or email'} value={search} onChange={event => { setPage(1); setSearch(event.target.value); }} /><select aria-label="Filter by status" value={status} onChange={event => { setPage(1); setStatus(event.target.value); }}><option value="">All statuses</option><option value="submitted">Submitted</option></select></div><section className="admin-content-card table-wrap"><table><thead><tr><th>Enquiry ID</th><th>Name</th><th>Course</th><th>Submitted At</th><th>Action</th></tr></thead><tbody>{rows.map(row => <tr key={row.id}><td><Link className="enquiry-number" href={`/admin/enquiries/${row.id}`}>{row.enquiry_number}</Link></td><td><strong className="candidate-name">{row.name}</strong><small className="table-secondary">{row.email}</small></td><td>{row.course}</td><td>{new Date(row.created_at).toLocaleString()}</td><td><Link className="dashboard-view-button" href={`/admin/enquiries/${row.id}`}>View</Link></td></tr>)}{rows.length === 0 && <tr><td className="empty-state" colSpan={5}>{search ? 'No enquiries match your search.' : 'No enquiries have been submitted yet.'}</td></tr>}</tbody></table></section><nav className="pagination"><button className="btn-secondary" disabled={page === 1} onClick={() => setPage(page - 1)}>Previous</button><span>Page {page} of {pageCount}</span><button className="btn-secondary" disabled={page >= pageCount} onClick={() => setPage(page + 1)}>Next</button></nav></div></main>;
}
