'use client';

import { useEffect, useState } from 'react';
import { Button } from '@/components/ui/Button';
import { Toast } from '@/components/ui/Toast';
import type { FormQuestion, QuestionType } from '@/types/form-question';

type DraftQuestion = FormQuestion;
const empty: Omit<FormQuestion, 'id' | 'created_at' | 'updated_at'> = { field_key: '', label: '', type: 'text', number_format: 'integer', required: false, allow_alphabets: true, allow_numbers: true, allow_special_characters: true, max_length: 255, options: [], display_order: 0, active: true, placeholder: '' };
const clone = (questions: DraftQuestion[]) => questions.map(question => ({ ...question, options: [...question.options] }));

export function QuestionsManager() {
  const [saved, setSaved] = useState<DraftQuestion[]>([]);
  const [draft, setDraft] = useState<DraftQuestion[]>([]);
  const [search, setSearch] = useState('');
  const [editingId, setEditingId] = useState<string | null>(null);
  const [editingSnapshot, setEditingSnapshot] = useState<DraftQuestion | null>(null);
  const [form, setForm] = useState<Omit<FormQuestion, 'id' | 'created_at' | 'updated_at'>>(empty);
  const [optionsText, setOptionsText] = useState('');
  const [notice, setNotice] = useState<{ text: string; error?: boolean } | null>(null);
  const [dragged, setDragged] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);
  const [deleteTarget, setDeleteTarget] = useState<DraftQuestion | null>(null);
  const [deleteText, setDeleteText] = useState('');

  async function load() { const response = await fetch('/api/admin/form-questions', { cache: 'no-store' }); if (response.ok) { const data = clone((await response.json()).data ?? []); setSaved(data); setDraft(clone(data)); } else setNotice({ text: 'Unable to load questions.', error: true }); }
  useEffect(() => { void load(); }, []);
  const hasChanges = JSON.stringify(saved) !== JSON.stringify(draft);
  const visible = draft.filter(question => `${question.field_key} ${question.label}`.toLowerCase().includes(search.toLowerCase()));
  function open(question?: DraftQuestion) { const value = question ? { ...question, options: [...question.options] } : { ...empty, display_order: draft.length ? Math.max(...draft.map(item => item.display_order)) + 10 : 10 }; setEditingId(question?.id ?? `new-${Date.now()}`); setEditingSnapshot(question ? { ...question, options: [...question.options] } : null); setForm(value); setOptionsText(question?.options.join('\n') ?? ''); }
  function update(name: string, value: unknown) { setForm(previous => ({ ...previous, [name]: value })); }
  function cancelEdit() { if (editingId?.startsWith('new-')) setDraft(previous => previous.filter(question => question.id !== editingId)); else if (editingSnapshot) setDraft(previous => previous.map(question => question.id === editingId ? editingSnapshot : question)); setEditingId(null); setEditingSnapshot(null); setForm(empty); setOptionsText(''); }
  function applyEdit(event: React.FormEvent) { event.preventDefault(); if (!editingId) return; const question = { ...form, options: form.type === 'select' ? optionsText.split('\n').map(value => value.trim()).filter(Boolean) : [], id: editingId } as DraftQuestion; setDraft(previous => previous.some(item => item.id === editingId) ? previous.map(item => item.id === editingId ? question : item) : [...previous, question]); setEditingId(null); setEditingSnapshot(null); setForm(empty); setOptionsText(''); }
  function requestRemove(question: DraftQuestion) { setDeleteTarget(question); setDeleteText(''); }
  function removeConfirmed() { if (!deleteTarget || deleteText !== 'DELETE') return; if (editingId === deleteTarget.id) cancelEdit(); setDraft(previous => previous.filter(question => question.id !== deleteTarget.id)); setDeleteTarget(null); setDeleteText(''); setNotice({ text: 'Question marked for deletion. Save Changes to apply it.' }); }
  function drop(targetId: string) { if (!dragged || dragged === targetId) return; const next = [...draft]; const from = next.findIndex(item => item.id === dragged); const to = next.findIndex(item => item.id === targetId); const [item] = next.splice(from, 1); next.splice(to, 0, item); setDraft(next.map((question, index) => ({ ...question, display_order: (index + 1) * 10 }))); setDragged(null); }
  async function saveChanges() { if (saving) return; setSaving(true); setNotice(null); try { const savedIds = new Set(saved.map(question => question.id)); const deletedIds = saved.filter(question => !draft.some(item => item.id === question.id)).map(question => question.id); const questions = draft.map(({ created_at: _created, updated_at: _updated, ...question }) => savedIds.has(question.id) ? question : { ...question, id: undefined }); const response = await fetch('/api/admin/form-questions', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ questions, deletedIds, deleteConfirmation: deletedIds.length ? 'DELETE' : undefined }) }); const result = await response.json(); if (!response.ok) { setNotice({ text: result.error ?? 'Unable to save changes.', error: true }); return; } const data = clone(result.data ?? []); setSaved(data); setDraft(clone(data)); setNotice({ text: 'Changes saved successfully' }); } catch { setNotice({ text: 'Unable to save changes.', error: true }); } finally { setSaving(false); } }

  return <main className="container admin-shell"><header className="admin-header"><div><p className="eyebrow">Form configuration</p><h1>Questions</h1><p className="admin-subtitle">Manage the questions shown on the public enquiry form.</p></div><div>{editingId && form.type === 'number' && <label>Number format<select aria-label="Number format" value={form.number_format} onChange={event => update('number_format', event.target.value)}><option value="integer">Integer</option><option value="decimal">Decimal</option></select></label>}<Button onClick={() => open()}>Add question</Button></div></header>
    <section className="admin-content-card questions-card"><div className="questions-toolbar"><input aria-label="Search questions" placeholder="Search questions" value={search} onChange={event => setSearch(event.target.value)} /><div className="questions-save-area">{hasChanges && <span className="unsaved-indicator">Unsaved changes</span>}<Button variant="secondary" disabled={!hasChanges || saving} onClick={saveChanges}>{saving ? 'Saving...' : 'Save Changes'}</Button></div></div>{notice && <Toast message={notice.text} error={notice.error} onClose={() => setNotice(null)} />}
      <div className="table-wrap"><table><thead><tr><th>Order</th><th>Question</th><th>Type</th><th>Required</th><th>Validation</th><th>Status</th><th>Actions</th></tr></thead><tbody>{visible.map((question, index) => <tr key={question.id} className={editingId === question.id ? 'question-row-editing' : ''} draggable={!editingId} onDragStart={() => setDragged(question.id)} onDragOver={event => event.preventDefault()} onDrop={() => drop(question.id)}><td>{index + 1}</td><td><strong>{question.label}</strong><small className="question-key">{question.field_key}</small>{editingId === question.id && <span className="editing-badge">Editing</span>}</td><td>{question.type}</td><td>{question.required ? 'Yes' : 'No'}</td><td>{question.max_length} chars{question.type === 'number' ? ', numeric' : ''}</td><td><span className="status-badge">{question.active ? 'Active' : 'Disabled'}</span></td><td className="question-actions"><button type="button" onClick={() => open(question)}>Edit</button><button type="button" onClick={() => requestRemove(question)}>Delete</button></td></tr>)}</tbody></table></div>
    </section>
    {editingId && <div className="modal-backdrop"><form className="question-dialog" onSubmit={applyEdit}><div className="section-heading"><h2>{editingSnapshot ? 'Edit question' : 'Add question'}</h2><button type="button" onClick={cancelEdit}>Cancel</button></div><div className="question-form-grid"><label>Field key<input required pattern="[A-Za-z][A-Za-z0-9_]*" value={form.field_key} disabled={!!editingSnapshot} onChange={event => update('field_key', event.target.value)} /></label><label>Label<input required value={form.label} onChange={event => update('label', event.target.value)} /></label><label>Type<select value={form.type} onChange={event => { update('type', event.target.value as QuestionType); if (event.target.value !== 'select') setOptionsText(''); }}>{['text', 'number', 'email', 'date', 'textarea', 'select', 'phone'].map(type => <option key={type}>{type}</option>)}</select></label><label>Max length<input required type="number" min="1" max="10000" value={form.max_length} onChange={event => update('max_length', Number(event.target.value))} /></label><label className="field-full">Placeholder<input value={form.placeholder ?? ''} onChange={event => update('placeholder', event.target.value)} /></label>{form.type === 'select' && <label className="field-full">Options, one per line<textarea value={optionsText} onChange={event => setOptionsText(event.target.value)} /></label>}<label><input type="checkbox" checked={form.active} onChange={event => update('active', event.target.checked)} /> Active</label><label><input type="checkbox" checked={form.required} onChange={event => update('required', event.target.checked)} /> Required</label><label><input type="checkbox" checked={form.allow_alphabets} onChange={event => update('allow_alphabets', event.target.checked)} /> Allow alphabets</label><label><input type="checkbox" checked={form.allow_numbers} onChange={event => update('allow_numbers', event.target.checked)} /> Allow numbers</label><label><input type="checkbox" checked={form.allow_special_characters} onChange={event => update('allow_special_characters', event.target.checked)} /> Allow special characters</label></div><Button type="submit">Apply to draft</Button></form></div>}
    {deleteTarget && <div className="modal-backdrop"><section className="question-dialog" role="dialog" aria-modal="true" aria-labelledby="delete-question-title"><h2 id="delete-question-title">Delete question?</h2><p>This question will be permanently deleted when you save changes. Type <strong>DELETE</strong> to confirm.</p><input autoFocus value={deleteText} onChange={event => setDeleteText(event.target.value)} placeholder="Type DELETE" aria-label="Type DELETE to confirm" /><div className="dialog-actions"><button type="button" onClick={() => setDeleteTarget(null)}>Cancel</button><button type="button" className="danger-button" disabled={deleteText !== 'DELETE'} onClick={removeConfirmed}>Delete</button></div></section></div>}
  </main>;
}