import { z } from 'zod';

export const enquirySchema = z.object({
  course: z.string().trim().min(1, 'Course is required'),
  name: z.string().trim().min(1, 'Name is required'),
  dob: z.string().trim().min(1, 'DOB is required'),
  gender: z.enum(['M', 'F', 'Other', '']).default(''),
  motherName: z.string().trim().min(1, 'Mother name is required'),
  fatherName: z.string().trim().min(1, 'Father name is required'),
  address: z.string().trim().min(1, 'Address is required'),
  mobile1: z.string().regex(/^\d{10}$/, 'Enter a 10-digit mobile number'),
  mobile2: z.string().refine((value) => value === '' || /^\d{10}$/.test(value), 'Enter a 10-digit mobile number or leave blank'),
  email: z.string().email('Enter a valid email').or(z.literal('')),
  class10Percent: z.string().trim().min(1, 'Class 10 marks are required'),
  class12Stream: z.string().default(''),
  class12Percent: z.string().trim().min(1, 'Class 12 marks are required'),
  physicsMarks: z.string().default(''),
  chemistryMarks: z.string().default(''),
  mathsMarks: z.string().default(''),
  biologyMarks: z.string().default(''),
  csMarks: z.string().default(''),
  schoolNameWithState: z.string().default(''),
  neetUgScore: z.string().default(''),
  neetPgScore: z.string().default(''),
  category: z.string().default(''),
  cuetScoreRank: z.string().default(''),
  cetScoreRank: z.string().default(''),
  clatScoreRank: z.string().default(''),
  catScoreRank: z.string().default(''),
  jeeMainsCrl: z.string().default(''),
  percentile: z.string().default(''),
  pcmPercent: z.string().default(''),
  pcbPercent: z.string().default(''),
  collegeUniversityName: z.string().default(''),
  courses: z.string().default(''),
  marks: z.string().default(''),
  reference: z.string().default(''),
  signatureDataUrl: z.string().default(''),
});

export type EnquiryInput = z.infer<typeof enquirySchema>;
